git.md - put the GitHub token content in a collapsed section
aristanetworks/avd-workshops pull request #135
Opened 2024-03-10 00:34 UTC by mjbear

git.md - put the GitHub token content in a collapsed section

2024-03-11 12:26 UTC, mthiel117 commented
Please change to not use inline HTML.  

Also, please use `mkdocs serve` to review your desired changes.

2024-03-11 12:27 UTC, mthiel117 requested changes

2024-03-11 12:27 UTC, mthiel117 commented on workshops/git.md
> +<details>
Please change to not use inline HTML.

Also, please use mkdocs serve to review your desired changes.

2024-03-11 12:27 UTC, mthiel117 commented on workshops/git.md
> +    <summary>When not using the ATD lab IDE, generate a GitHub personal access token (click to expand)</summary>
Please change to not use inline HTML.

Also, please use mkdocs serve to review your desired changes.

2024-03-11 13:01 UTC, mjbear commented
> Please change to not use inline HTML.
> 
> Also, please use `mkdocs serve` to review your desired changes.

Certainly.
I should have used an mkdocs [admonition](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types) instead of the [general collapsible HTML markup](https://github.com/squidfunk/mkdocs-material/discussions/3711#discussioncomment-8225404). Apologies.

Will do.

2024-03-11 13:15 UTC, mjbear commented
@mthiel117
This has been remedied by using an admonition for the collapsed section.

2024-03-13 19:14 UTC, JulioPDX approved these changes
Great add, thank you

2024-03-13 21:13 UTC, JulioPDX commented
fixes #127

2024-03-14 01:03 UTC, mthiel117 approved these changes
LGTM.  I like it.  Thanks

2024-03-14 01:03 UTC, merged